### ISSUE TITLE
Are you tracking my use of moz:// URLs?

### ISSUE THREAD

**Issue by martinthomson** [mozilla/moz-handler#1]
Wouldn't it be easier to do the redirection in the addon?

**Comment by chutten** [comment]
I think the idea is to do the redirection within the addon, but based on a list of urls that are stored outside of it. This way the redirections can be updated without forcing the user to update the add-on.

**Comment by mykmelez** [comment]
> Are you tracking my use of moz:// URLs?

I'm not!

The addon redirects `moz:` URLs to https://mozilla.github.io/moz-handler/?u=MOZ_URL, where *MOZ_URL* is the URL you loaded. That extracts the keyword after moz://a/ (more accurately: the substring starting from the 8th character in the moz: URL), looks it up in a hash, and redirects to the URL associated with that keyword. It doesn't record the request or do any analytics.

GitHub, however, might do some tracking. It certainly has the capacity to do so, since it hosts mozilla.github.io.

> Wouldn't it be easier to do the redirection in the addon?

Not really. The API that the extension uses is similar to the one that is being implemented by @mixedpuppy for WebExtensions in [bug 1271553](https://bugzilla.mozilla.org/show_bug.cgi?id=1271553). And it only allows the extension to register a URL to which requests are redirected. It doesn't allow the extension to handle the URL programmatically.

I could implement this entirely within the extension using other APIs, per @Mossop's work in [bug 1331968](https://bugzilla.mozilla.org/show_bug.cgi?id=1331968), but eventually I'd have to change that anyway, once WebExtensions become the only supported extensions.

**Comment by martinthomson** [comment]
> > Are you tracking my use of moz:// URLs?
>
> I'm not!

Ahh, my point is that I don't have any confidence that you aren't.  Let us stipulate that you can update the addon at any time to change how it works, so I'm going to have to trust you anyway.  And in this case, it looks like you are running off github pages, so maybe I can see that code too (I thought that I could, but don't actually know how you are doing this). But...

As long as we lack the ability to do what bug 1331968 does in a web extension, we are giving sites only one way to do this sort of thing: the (potentially) bad way.  And that bad way isn't great for performance either.  It's a new connection just to get something that the addon should know anyway. The only case where you should be relying on a site for this is where you need a relatively large database of redirects.  I guess that I'll have jump in on bug 12715553 then.

**Comment by mykmelez** [comment]
> (I thought that I could, but don't actually know how you are doing this)

The GitHub Pages site for this project (https://mozilla.github.io/moz-handler/) is generated from the docs/ directory within this repository:

https://github.com/mozilla/moz-handler/tree/master/docs

That directory contains a single file, index.html, with both the data and the logic to determine and execute the redirects:

https://github.com/mozilla/moz-handler/blob/master/docs/index.html

**Comment by floatingatoll** [comment]
@martinthomson - To ask a triage sort of question: Do you have a specific issue with this project that could actually be resolved usefully by us under today's Firefox? Or, are you raising awareness of the issues in bug 12715553 (sic) and bug 1331968, and it's okay if this issue is closed with the discussion above as its sole output?

**Comment by mykmelez** [comment]
FWIW, I agree that it'd be preferable for the extension to handle this internally. It'd be better for privacy (or at least potential privacy). And in theory it should be more performant (although conversation in bug 1271553 notes that there are perf implications to on-main-thread parsing of URLs that we'd have to avoid).

However, at this point, I don't see an opportunity to do internal redirection long-term, given the limitations of the proposed WebExtensions API that I'll need to use once WebExtensions are the only extensions. So I don't think there's anything more we can do here.

**Comment by chutten** [comment]
We can have the APIs extended. Mozilla's been very receptive to reasonable extension requests from addon authors.

**Comment by mykmelez** [comment]
> We can have the APIs extended. Mozilla's been very receptive to reasonable extension requests from addon authors.

Indeed, and Martin did say that he'd be jumping into bug 1271553. So I'll leave this open pending the outcome of that conversation.
