### ISSUE TITLE
Plugin doesn't work under latest Nightly version

### ISSUE THREAD

**Issue by airon90** [mozilla/moz-handler#13]
The plugin in Mozilla Addons platform doesn't work under latest Firefox Nightly version

**Comment by lidel** [comment]
Sounds like a gentle reminder to give https://bugzilla.mozilla.org/show_bug.cgi?id=1271553 some love.

**Comment by mykmelez** [comment]
I think the current issue is that Firefox now has its own moz: handler, per https://bugzilla.mozilla.org/show_bug.cgi?id=1331968, and the one provided by this extension doesn't override it.

The fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1271553 shouldn't (yet) be necessary, since the extension already redirects requests to a server. However, it (or the equivalent) may become necessary, once the Add-on SDK APIs are disabled.

**Comment by Natim** [comment]
Apparently Bug 1331968 is not shipping in release.
